apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html-container
        image: yellammam/test:latest
        ports:
        - containerPort: 80
